// Generated by CoffeeScript 1.4.0
(function() {
  var tasteProfileBasic, wineList;

  tasteProfileBasic = {
    category: 1,
    angularity: 0,
    acid: 50,
    tannin: 50,
    alcohol: 50
  };

  wineList = [
    {
      category: 1,
      angularity: 0,
      acid: 50,
      tannin: 50,
      alcohol: 50
    }, {
      category: 3,
      angularity: 0,
      acid: 50,
      tannin: 50,
      alcohol: 50
    }, {
      category: 6,
      angularity: 0,
      acid: 50,
      tannin: 50,
      alcohol: 50
    }
  ];

  module.exports({
    tasteProfileBasic: tasteProfileBasic,
    wineList: wineList
  });

}).call(this);
