// Generated by CoffeeScript 1.4.0
(function() {
  var should, utils;

  should = require('should');

  utils = require('../lib/util');

  describe('Squared Euclidean Distance function', function() {
    it('should calculate correctly for 1 dimension', function() {
      return utils.distance({
        a: 1
      }, {
        a: 5
      }).should.eql(16);
    });
    it('should calculate correctly for 2 dimensions', function() {
      return utils.distance({
        a: 1,
        b: 3
      }, {
        a: 5,
        b: 5
      }).should.eql(20);
    });
    return it('should calculate correctly for 3 dimensions', function() {
      return utils.distance({
        a: 1,
        b: 3,
        c: -2
      }, {
        a: 5,
        b: 5,
        c: 2
      }).should.eql(36);
    });
  });

  describe('Standard Deviation', function() {
    it('should be 0 with array of equal numbers', function() {
      return utils.stdv([1, 1, 1, 1, 1]).should.eql(0);
    });
    return it('should calculate stdv given an array of numbers', function() {
      return utils.stdv([600, 470, 170, 430, 300]).should.eql(147.32277488562318);
    });
  });

  describe('Standardize', function() {
    return it('returns the array in units of stdv from mean', function() {
      return utils.standardize([600, 470, 170, 430, 300]).should.eql([1.398290251863176, 0.5158740735029193, -1.5204709534822884, 0.24436140323822492, -0.6380547751220317]);
    });
  });

}).call(this);
