// Generated by CoffeeScript 1.4.0
(function() {
  var nearestNeighbor, should;

  should = require('should');

  nearestNeighbor = require('../lib/main');

  describe('K Nearest Neighbor', function() {
    return describe('with basic wine testCase', function() {
      beforeEach(function() {
        var testCase;
        return testCase = require('./test_case_simple');
      });
      it('should return the nearest neighbor');
      it('should return 5 nearest neighbors, sorted by distance');
      return it('should return all of Y sorted by distance if Y.length < 5');
    });
  });

}).call(this);
