// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(subject, objects, options) {
    var attr, o, _results;
    if (arguments.length < 2) {
      throw new Error('Expecting at least 2 arguments');
    }
    if (!(Array.prototype.slice.call(arguments).every(function(i) {
      return i && typeof i === 'object';
    }))) {
      throw new Error('Expecting object arguments');
    }
    if (!Array.isArray(arguments[1])) {
      throw new Error('Expecting an array as second argument');
    }
    if (!objects.length) {
      return [];
    }
    _results = [];
    for (attr in subject) {
      _results.push((function() {
        var _i, _len, _results1;
        _results1 = [];
        for (_i = 0, _len = objects.length; _i < _len; _i++) {
          o = objects[_i];
          if (!(attr in o)) {
            throw new Error("Missing attribute '" + attr + "' in '" + (JSON.stringify(o)) + "'");
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

}).call(this);
