// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(subject, objects, options) {
    if (arguments.length < 2) {
      throw new Error("Expecting at least 2 arguments");
    }
    return arguments;
  };

}).call(this);
